version: 2

models:
  - name: Dim_State
    columns:
      - name: State_Name
        data_tests:
          - unique
          - not_null
      - name: State_ID
        data_tests:
          - unique            
  - name: Dim_County
    columns:
      - name: County_Name
        data_tests:
          - not_null
      - name: State_Abbreviation
        data_tests:
          - not_null
      - name: County_ID
        data_tests:
          - unique                    
                  
        